# Generated by Django 3.1.4 on 2021-09-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ta_Da',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('travel_cost', models.FloatField()),
                ('lunch_cost', models.FloatField()),
                ('instrument_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('Paid', models.CharField(max_length=20)),
            ],
        ),
    ]
