# Generated by Django 3.1.4 on 2021-09-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta_da',
            name='date',
            field=models.DateField(),
        ),
    ]
